# More Python Basics

*This section uses content from the [Python section](https://melaniewalsh.github.io/Intro-Cultural-Analytics/02-Python/00-Python.html#) of Melanie Walsh's Introduction to Cultural Analytics & Python.*

The purpose of this notebook is to give you a stronger, more complete foundation for "vanilla" (built-in) Python by discussing loops, as well as to introduce the NumPy library. **The goal of this lab is to give you the tools you need to start building robust functions which can make useful calculations on large datasets.**

To that end, we'll cover the following:

1. More Python Basics
    - Loops
    - Generator Iterators
2. NumPy
    - NumPy Arrays
    - Array Operations

## Loops

Python provides two different types of loop: the `for` loop, and the `while` loop. The `for` loop iterates a block of code through the elements of some iterable (i.e., list-like) object, whereas the `while` loop executes a block of code as long as some condition is met. In other words, `for` loops are best suited for *finite* (definite) iteration, and `while` loops are best suited for *potentially infinite* (indefinite) iteration. For our purposes, **every loop should be finite**, so practically, any `while` loop can (and often should) be converted into a `for` loop.

We will introduce both here, but since `while` loops can sometimes result in infinite loops, often causing the computer to freeze up, our focus in this class will be on `for` loops.

### `for` loops

Again, a `for` loop will execute a block of code for each item in a list-like object. On the first line, we type the English word `for`, a new variable name for each item in the list, the English word `in`, the name of the list-like object, and then a colon `:`. All instructions for a `for` loop must be indented.

In [1]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# suppose we want to print the odd numbers in `numbers` that are 5 or less
for number in numbers:
    # we can "skip" values using continue
    if number == "two":
        continue
    
    # remember what the `%` symbol does
    elif number % 2 == 1:
        print(f"{number} is an odd number.")
    
    # `break` completely stops the looping process
    elif number > 5:
        break

1 is an odd number.
3 is an odd number.
5 is an odd number.


* In the same way that variables (in general) should be descriptively named, the iterating variable of for-loops (between `for` and `in`) should be descriptive of what is held behind it.
* As it is usually difficult to determine what is going on, print statements help to "debug" the contents of variables as you go. **Use looped print statements sparingly!**

### `while` loops

**<span style='color:red;'>CAUTION:</span>** Do your best to **avoid using `while` loops at all**; try to convert them into a `for` loop (above) whenever possible.

In [41]:
# start with `while`, the condition to be met, and then the block of code
i = 1
j = 2

while j > i:
    if j in [10, 1e2, 1e3, 1e4, 1e5, 1e6, 1e7]:
        print("j =", j)
    elif j == 1e8:
        print("j is really big now, and it's just getting bigger ...")
    j += 1

j = 10
j = 100
j = 1000
j = 10000
j = 100000
j = 1000000
j = 10000000
j is really big now, and it's just getting bigger ...


KeyboardInterrupt: 

<font color='darkblue'>You can interrupt the above code with the "**I, I**" shortcut, or clicking the "stop" button.</font>

`while` loops should only be *considered* for the following cases:
* infinite looping, where there might not ever be an end (mostly in software engineering)
* situations where the object being iterated through changes with each loop.

The latter of these is more common, but even then a `for` loop may still do the job.

## Generator Iterators

In Python, an **iterable** is an object *containing* one or more data elements that a `for` loop can iterate over. For example, lists, tuples, dictionaries, and sets are all iterable objects. They provide multiple elements of data that you can iterate over.

However, consider two alternate scenarios:

1. We do not know all the elements to be iterated over, but we know how they are generated.
2. We know the elements to be iterated over, but we do not want them taking up memory until it is their "turn".

In either of these cases, we can use the Python [generator](https://realpython.com/introduction-to-python-generators/) iterator to 'stream' elements to iterate over.

Three common built-in Python generators are `range()`, `enumerate()`, and `zip()`.

### `range`

`range()` generates numbers in a sequence, from `(start, stop, step)`.

In [42]:
[0, 1, 2]

[0, 1, 2]

In [43]:
# on it's own, an iterator is just a function
range(3)

range(0, 3)

We can create our own generator using the `yield` keyword.

In [44]:
def my_range(n):
    i = 0
    while i < n:
        i += 1
        yield((i, f"this is {i}"))

In [45]:
instance_of_my_range = my_range(5)

In [46]:
for i in instance_of_my_range:
    print(i)

(1, 'this is 1')
(2, 'this is 2')
(3, 'this is 3')
(4, 'this is 4')
(5, 'this is 5')


In [47]:
# what happens when the generator "runs out" ...
next(instance_of_my_range)

StopIteration: 

Or, we can use a [generator expression](https://peps.python.org/pep-0289/), which is similar to a list comprehension:

In [53]:
# generator comprehension
gen_list = (c for c in ['a', 'b', 'c'])
gen_list

<generator object <genexpr> at 0x10628e190>

In [54]:
next(gen_list)

'a'

The basic `range` generator behaves as expected ...

In [99]:
# by default, the first value will be 0, and step is 1
for i in range(3):
    print(i)

0
1
2


In [55]:
# we can iterate from 2 to 20, by step size 3
for i in range(2, 20, 3):
    print(i)

2
5
8
11
14
17


In [56]:
# we can even go backwards
for i in range(5, 1, -1):
    print(i)

5
4
3
2


### `enumerate`

If we are working with a defined iterable (like a list), but we also want to log the index of each element as we iterate over it, we can use `enumerate`.

In [57]:
names = ['astrid', 'jamaal', 'timo', 'hyewon']

# notice the order of `i` and `element` here
for i, element in enumerate(names):
    print(f"index: {i} ... element: {element}")

index: 0 ... element: astrid
index: 1 ... element: jamaal
index: 2 ... element: timo
index: 3 ... element: hyewon


### `zip`

Suppose we have two different iterables that we would like to combine into a list of tuples (or a dictionary).

In [58]:
keys =   ["a", "b", "c"]
values = [1,     2,   3]

kv_dict = {}
kv_list = []

for k, v in zip(keys, values):
    # print(k, v)
    
    kv_dict[k] = v
    kv_list.append((k, v))

In [59]:
kv_dict

{'a': 1, 'b': 2, 'c': 3}

In [60]:
kv_list

[('a', 1), ('b', 2), ('c', 3)]

Alternatively, we could use list/dictionary comprehensions ...

In [61]:
keys =   ["a", "b", "c", "a"]
values = [1,     2,   3,  4 ]

In [62]:
[(k, v) for k, v in zip(keys, values)]

[('a', 1), ('b', 2), ('c', 3), ('a', 4)]

In [63]:
{k:v for k, v in zip(keys, values)}

{'a': 4, 'b': 2, 'c': 3}

### EXERCISE

The Fibonacci Series starts with 0 and 1. Each of the following numbers are the sum of the previous two numbers in the series. So, the first element is 0, the next element is 1, the next is 1, and the next is 2, and so on.

Write a function which *prints* the following, given a number `n`:

    Fibonacci 1 = 0
    Fibonacci 2 = 1
    Fibonacci 3 = 1
    ...
    Fibonacci n = ?

In [12]:
# your code here

# Intro to NumPy

*This is a summarized version of [NumPy's absolute beginners tutorial](https://numpy.org/doc/stable/user/absolute_beginners.html). Each sub-section title here links to its corresponding section in the tutorial.*

[NumPy](https://numpy.org/doc/stable/user/absolute_beginners.html) (Numerical Python) is an enormous open source Python library that is *easily* the universal standard for working with numerical data in Python. Its users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. NumPy improves on numerical programming in Python by introducing optimized low-level programming, and a library of high-level mathematical functions that operate on arrays and matrices.

If you haven't already, you should be able to install NumPy into your **pip** environment for this course using `pip install numpy`.

In [64]:
import numpy as np

## [NumPy Arrays](https://numpy.org/doc/stable/user/absolute_beginners.html#what-is-an-array)

The NumPy n-dimensional array (`ndarray`) is the central data structure of the NumPy library. We can think of it roughly as a vector (with 1-dimension) or a matrix (with 2-dimensions), but it might be better to think of it as a "[tensor](https://www.kdnuggets.com/2018/05/wtf-tensor.html)" (with 3 or more, n-dimensions). NumPy arrays are homogeneous, i.e., the data type is consistent across all elements (this allows for optimized calculations). The `shape` of the array is a tuple of integers giving the size of the array along each dimension. *For math people, think about an $n$-dimensional NumPy array as points on a "grid" in $n$-space.*

Note: NumPy is *vast* and has capabilities reaching far beyond what is included in this notebook. Again, **this is just an introduction to NumPy.**

In [65]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

In [66]:
# `.ndim` gives us the number of dimensions of our array
a.ndim

2

In [67]:
# `shape` gives the length of each dimension
a.shape

(2, 3)

In [68]:
# `size` is the number of elements in the array
a.size

6

Each dimension is called an **axis**, working your way from "outside" to "inside". E.g., in `a`, the rows are `axis 0`, and the columns are `axis 1`.

### [Building Arrays](https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-create-a-basic-array)

There are many different ways to build arrays, but a few interesting ones are using the `arange` and `linspace` functions.

In [69]:
# arange is similar the `range` we've seen above
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [70]:
# linspace creates evenly spaced elements in an array
np.linspace(0, 5, num=11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [71]:
# convert a 1-d array to a 2-d array by adding an axis
np.arange(1, 10, 2)[:, np.newaxis]

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [72]:
# using `reshape` in this way is another way to add an axis
a = np.arange(3, 10, 2).reshape(-1, 1)
b = np.arange(4, 20, 4).reshape(-1, 1)

# concatenate is one way to merge arrays together
c = np.concatenate((a, b), axis=1)
c

array([[ 3,  4],
       [ 5,  8],
       [ 7, 12],
       [ 9, 16]])

In [73]:
# another example of reshaping
c.reshape(2, 4)

array([[ 3,  4,  5,  8],
       [ 7, 12,  9, 16]])

In [74]:
c.reshape(-1, 1)

array([[ 3],
       [ 4],
       [ 5],
       [ 8],
       [ 7],
       [12],
       [ 9],
       [16]])

In [75]:
# we can "vertically" stack using vstack
a = np.array([3,  4,  5,  8])
b = np.array([7, 12,  9, 16])

np.vstack((a, b))

array([[ 3,  4,  5,  8],
       [ 7, 12,  9, 16]])

In [76]:
# or we could "horizontally" stack using hstack
a = np.array([3,  4,  5,  8])[:, np.newaxis]
b = np.array([7, 12,  9, 16])[:, np.newaxis]

np.hstack((a, b))

array([[ 3,  7],
       [ 4, 12],
       [ 5,  9],
       [ 8, 16]])

You can also [flatten](https://numpy.org/doc/stable/user/absolute_beginners.html#reshaping-and-flattening-multidimensional-arrays) arrays, which is a slightly different take on "reshaping". Here, we reduce the values of a multi-dimensional array into a flat, 1-D array.

In [77]:
x = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### [Indexing and Slicing](https://numpy.org/doc/stable/user/absolute_beginners.html#indexing-and-slicing)

There are several ways to extract "slices" of an array. The most basic mirrors how we'd slice a list (i.e., using `start:stop:step` syntax).

In [78]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a = np.arange(1, 10+1)

a[2:9:2]

array([3, 5, 7, 9])

We can also use boolean (True/False) filtering based on logical conditions. In NumPy, the **and** operator is `&`, and the **or** operator is `|`.

In [79]:
a = np.array([[1 , 2,  3,  4], 
              [5,  6,  7,  8], 
              [9, 10, 11, 12]])

In [80]:
(a == 1)

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [81]:
(a > 5)

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [82]:
mask = (a == 1) | (a > 5)
mask

array([[ True, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [83]:
a[mask]

array([ 1,  6,  7,  8,  9, 10, 11, 12])

Here, `np.where` returns values based on a condition, and we can use the `np.nan` (Not A Number, or "Null") value to represent missing values.

In [84]:
np.where(mask, a, np.nan)

array([[ 1., nan, nan, nan],
       [nan,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

We can also use the `[:]` notation to extract different kinds of slices.

In [87]:
# first "vector" (i.e., the first row)
a[0,:]

# a[0,]  # shorthand!

array([1, 2, 3, 4])

In [88]:
# the second value for each row; and think of `:` as all appropriate values
a[:, 1][:, np.newaxis]

array([[ 2],
       [ 6],
       [10]])

In [90]:
# using [:] notation to get vertical column
a[:, 1:2]

array([[ 2],
       [ 6],
       [10]])

<span style='color:red;'>**Important Note on Slicing:**</span> Slices of arrays are *references* to the original array. **If you need to extract a permanently "independent" slice of an array, you need to `copy` it.**

In [91]:
a = np.array([[1 , 2,  3,  4], 
              [5,  6,  7,  8]])

# a copy to check later
a_copy = a.copy()

# here, we "extract" (refer to) a slice of `a`
a_slice = a[:, :2]
a_slice

array([[1, 2],
       [5, 6]])

In [92]:
# here, we amend (mutate) that slice
a_slice[0, :] = np.array([9, 9])
a_slice

array([[9, 9],
       [5, 6]])

In [93]:
# we have then updated the original array, too
a

array([[9, 9, 3, 4],
       [5, 6, 7, 8]])

In [94]:
a_copy

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### [Random Generation](https://numpy.org/doc/stable/user/absolute_beginners.html#generating-random-numbers)

NumPy also has the capability to generate random numbers from various probability distributions.

In [95]:
# the uniform distribution is just one of *many* options
data = np.random.uniform(size=(2, 3))
data

array([[0.50142717, 0.00831845, 0.11666174],
       [0.95423295, 0.44159547, 0.96196636]])

In [97]:
# including a random seed ensures the "same random" generations with each run
gen = np.random.default_rng(seed=33)
gen.normal(loc=5, scale=1, size=(3, 2))

array([[5.39836997, 4.43717666],
       [5.58883494, 5.0421181 ],
       [3.42909948, 6.00165475]])

**This random seed no longer applies when run in a separate cell.**

In [101]:
gen.normal(loc=5, scale=1, size=(3, 2))

array([[5.55622219, 4.22720963],
       [4.51951097, 5.54377453],
       [3.70110324, 4.11984543]])

## Array Operations

NumPy provides all the standard mathematical operations you'd expect, but the difference now is that these operations are extremely fast, and they operate in a "vectorized" fashion. This can happen in three ways: element-wise, using what is called "broadcasting", or using standard mathematical matrix operations. We can also calculate aggregate values such as mean or minimum, etc.

### [Element-wise Operations](https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations)

In [102]:
# we can create an array of only ones
ones = np.ones((2, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [104]:
ones + a

array([[ 3.,  5.,  7.,  9.],
       [11., 13., 15., 17.]])

In [105]:
ones / a

array([[0.5       , 0.25      , 0.16666667, 0.125     ],
       [0.1       , 0.08333333, 0.07142857, 0.0625    ]])

### [Broadcasting](https://numpy.org/doc/stable/user/absolute_beginners.html#broadcasting)

When [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html) an operation between two arrays (with potentially different shapes), NumPy first compares their shapes element-wise, starting with the trailing (i.e. rightmost) dimension, and working its way left. Two dimensions are compatible when (a) they are equal, or (b) one of them is 1.

```
Compatible:
(4, 5, 2)
   (5, 1)             First, 1 works. Then, 5 = 5.

Not compatible:
(100, 4)
  (5, 2)             First, 4 ≠ 2 and neither are 1.
```

In [106]:
a = np.array([[1, 2],
              [4, 5],
              [7, 8]])
               
b = np.array([[3], 
              [2], 
              [1]])

In [107]:
# Notice how multiplying by `b` is broadcast "across" `a`
print(f"a shape: {a.shape}")
print(f"b shape: {b.shape}")
a * b

a shape: (3, 2)
b shape: (3, 1)


array([[ 3,  6],
       [ 8, 10],
       [ 7,  8]])

In [108]:
# the same happens with scalars
4 * b

array([[12],
       [ 8],
       [ 4]])

In [109]:
b

array([[3],
       [2],
       [1]])

In [110]:
# we an also broadcast across 2+ axes
c = np.array([1, 2, 3])

b * c

array([[3, 6, 9],
       [2, 4, 6],
       [1, 2, 3]])

### Matrix Arithmetic

Any array is essentially a matrix of values, and NumPy provides the standard matrix and vector operations. Here are just a few examples.

In [115]:
a = np.array([[1, 2],
              [3, 4],
              [5, 6]])

b = np.array([[9, 8, 7],
              [6, 5, 4]])

c = np.array([1, 2, 3])

In [112]:
# the @ symbol represents matrix multiplication
a @ b

array([[21, 18, 15],
       [51, 44, 37],
       [81, 70, 59]])

In [125]:
b @ c.reshape(-1, 1)

array([[46],
       [28]])

In [126]:
# np.dot works too
np.dot(a, b)

array([[21, 18, 15],
       [51, 44, 37],
       [81, 70, 59]])

In [127]:
c.dot(c)

np.int64(14)

In [ ]:
# type "Shift + Tab" in the parentheses to explore this data type ...
# np.int64()

In [128]:
# .T calculates the transpose (not for single rows/columns)
a.T

array([[1, 3, 5],
       [2, 4, 6]])

### [Aggregation](https://numpy.org/doc/stable/user/absolute_beginners.html#more-useful-array-operations)

Often, you'll want to calculate aggregate functions (e.g., mean, minimum, etc.) for a whole array, or for just rows/columns (or some other axis).

In [129]:
a = np.array([[ 3,  6,  9, 12, 15],
              [ 4,  8, 12, 16, 20]])

In [130]:
# we can calculate a minimum for all the data
a.min()

np.int64(3)

In [131]:
# or, just across an axis (here, across columns for each row)
a.min(axis=1)

array([3, 4])

In [132]:
a.mean(axis=0)

array([ 3.5,  7. , 10.5, 14. , 17.5])

In [133]:
a.sum(axis=1)

array([45, 60])

Given a vector of weights, NumPy can also calculate a weighted average.

In [134]:
w = np.array([1, 4, 1, 2, 5])

In [137]:
np.average(a, axis=1, weights=w).reshape(-1, 1)

array([[10.38461538],
       [13.84615385]])

The [unique](https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-get-unique-items-and-counts) function is helpful to find out the distinct values in a vector or tensor.

In [138]:
a = np.array([11, 11, 12, 13, 14, 16, 17, 11, 13, 11, 14, 18, 10, 14])

np.unique(a)

array([10, 11, 12, 13, 14, 16, 17, 18])

# Exercises

You can use the rest of the notebook as needed for the weekly exercise(s).